In [2]:
import numpy as np;
import pandas as pd;
import matplotlib.pyplot as plt;
import seaborn as sns;

import warnings
warnings.filterwarnings('ignore')

In [3]:
df2 = pd.read_csv ('it_survey.csv')

In [4]:
df2.head(50)

,Timestamp,Username,Name,Age,Sex,Strand in SHS,Prefer Skill,Major in College,Unnamed: 8
0,2023/05/05 7:13:39 PM GMT+8,hernandezkleyrann@gmail.com,Claire Ann Hernandez,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
1,2023/05/05 7:13:56 PM GMT+8,20-73559@g.batstate-u.edu.ph,Paolo D. Julongbayan,21,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
2,2023/05/05 7:16:37 PM GMT+8,hernandezkleyrann@gmail.com,Claire Ann Hernandez,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
3,2023/05/05 7:16:43 PM GMT+8,charlessebastiengualvez123@gmail.com,Charles Sebastien Gualvez,21,Male,ICT (Animation / Programming),"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
4,2023/05/05 7:17:43 PM GMT+8,jephthahlandicho1212@gmail.com,Jephthah Jehosaphat Landicho,21,Male,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
5,2023/05/05 7:18:24 PM GMT+8,20-73559@g.batstate-u.edu.ph,Paolo D. Julongbayan,21,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
6,2023/05/05 7:21:00 PM GMT+8,leirah.ningala@gmail.com,Leirah,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
7,2023/05/05 7:23:35 PM GMT+8,20-75518@g.batstate-u.edu.ph,Bryan Russel I. Rosel,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
8,2023/05/05 7:23:35 PM GMT+8,jhonrelremobatacwalog@gmail.com,Jhon Rel R. Walog,23,Male,CSS,"Network administration, Cybersecurity, or Netw...",Networking,NaN
9,2023/05/05 7:26:40 PM GMT+8,geraldgarciacapoon@gmail.com,Gerald G Capoon,20,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
10,2023/05/05 7:32:59 PM GMT+8,deanneanorico@gmail.com,Deanne Anorico,20,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,Network Administration
11,2023/05/05 7:33:51 PM GMT+8,camansag.mark@gmail.com,mark,21,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking,Network Administration
12,2023/05/05 7:34:37 PM GMT+8,aloe7812@gmail.com,Angelo Novero,21,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking,Network Administration;cybersecurity
13,2023/05/05 7:34:38 PM GMT+8,jakedecena.cahayon@gmail.com,Jake Angelo Cahayon,21,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking,Network Administration
14,2023/05/05 7:35:10 PM GMT+8,xanderm854@gmail.com,Kim Alexander Mendoza,22,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,Programming and predicting;Business Intelligence
15,2023/05/05 7:37:37 PM GMT+8,20-72800@g.batstate-u.edu.ph,Carl Joriz Mickeal S. Marasigan,20,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking,Connecting cables
16,2023/05/05 7:41:23 PM GMT+8,krisshaesteron24@gmail.com,Krissha Joy V. Esteron,20,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
17,2023/05/05 7:44:54 PM GMT+8,jhorelygabriel04@gmail.com,Jhorely C. Gabriel,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
18,2023/05/05 7:45:02 PM GMT+8,cristieandino25@gmail.com,Cristie Andino,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
19,2023/05/05 7:46:55 PM GMT+8,erlynandrin04@gmail.com,Erlyn S. Andrin,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
20,2023/05/05 7:48:14 PM GMT+8,20-77727@g.batstate-u.edu.ph,Erwin Zaragoza,21,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking,NaN
21,2023/05/05 7:48:38 PM GMT+8,singsonmaxine@gmail.com,Max,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Networking,NaN
22,2023/05/05 7:49:39 PM GMT+8,delosreyesmarrien75@gmail.com,Marrien Delos Reyes,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
23,2023/05/05 7:49:50 PM GMT+8,20-75214@g.batstate-u.edu.ph,Alison kaye reyes,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
24,2023/05/05 7:49:51 PM GMT+8,rogerzabala26@gmail.com,Roger L. Zabala Jr,22,Male,MARINE ENGINEERING,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
25,2023/05/05 7:49:52 PM GMT+8,pelaezpatriciaann@gmail.com,Patricia,20,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
26,2023/05/05 7:52:54 PM GMT+8,20-74201@g.batstate-u.edu.ph,Jessica Ann Ramos,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
27,2023/05/05 7:53:23 PM GMT+8,21-79604@g.batstate-u.edu.ph,"Lundag, Jherico",20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
28,2023/05/05 7:55:38 PM GMT+8,21-70142@g.batstate-u.edu.ph,Ma. Jan Floriane M. Natoc,20,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
29,2023/05/05 7:56:32 PM GMT+8,20-71915@g.batstate-u.edu.ph,Faye Villaluna,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
30,2023/05/05 8:01:42 PM GMT+8,jhosuavillaluna2@gmail.com,"Villaluna, Jhosua A.",18,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
31,2023/05/05 8:03:18 PM GMT+8,aciesnet02@gmail.com,Allen Carl Delas Alas,21,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking,NaN
32,2023/05/05 8:06:40 PM GMT+8,romnelgsolcied@gmail.com,Glenmor Decilos,18,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking,NaN
33,2023/05/05 8:08:38 PM GMT+8,20-75347@g.batstate-u.edu.ph,Richelle Concepcion V. Adrias,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
34,2023/05/05 8:09:40 PM GMT+8,20-76036@g.batstate-u.edu.ph,Kimberly Panganiban,21,Female,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
35,2023/05/05 8:14:21 PM GMT+8,ballesterosmean@gmail.com,Mary Ann Ballesteros,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
36,2023/05/05 8:14:57 PM GMT+8,20-72433@g.batstate-u.edu.ph,Kent Bryan Carbayar,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
37,2023/05/05 8:15:58 PM GMT+8,kylechadwick.aster@g.batstate-u.edu.ph,Kyle Aster,21,Male,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
38,2023/05/05 8:17:09 PM GMT+8,benilogaya@gmail.com,Benil Ogaya,23,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
39,2023/05/05 8:20:30 PM GMT+8,rodriguezreignoel@gmail.com,Reignoel Rodriguez,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
40,2023/05/05 8:24:31 PM GMT+8,NaN,Camilla Estrello,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
41,2023/05/05 8:27:19 PM GMT+8,NaN,Krissha Joy V. Esteron,20,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
42,2023/05/05 8:27:38 PM GMT+8,NaN,Czarina Bacit,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking,NaN
43,2023/05/05 8:30:54 PM GMT+8,NaN,Jerico Cabotaje,21,Male,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
44,2023/05/05 8:49:15 PM GMT+8,NaN,nics,21,Female,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
45,2023/05/05 8:50:48 PM GMT+8,NaN,Miguel Pelo,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
46,2023/05/05 8:53:03 PM GMT+8,NaN,John Paulo A. Bascuguin,23,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
47,2023/05/05 9:06:04 PM GMT+8,NaN,Edesa Ruedas,20,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
48,2023/05/05 9:50:15 PM GMT+8,NaN,Leo Delayola,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN
49,2023/05/05 10:12:38 PM GMT+8,NaN,Bryan Russel,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major,NaN

In [5]:
# sns.countplot(df2['Major in College'])

In [6]:
df2.drop(['Unnamed: 8', 'Name', 'Username', 'Timestamp'], axis = 1, inplace=True)

In [7]:
# df2.head(10)

In [40]:

df2.head(50)

,Age,Sex,Strand in SHS,Prefer Skill,Major in College
0,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
1,21,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
2,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
3,21,Male,ICT (Animation / Programming),"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
4,21,Male,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
5,21,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
6,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
7,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
8,23,Male,CSS,"Network administration, Cybersecurity, or Netw...",Networking
9,20,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking
10,20,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
11,21,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking
12,21,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking
13,21,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking
14,22,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
15,20,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking
16,20,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
17,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
18,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
19,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
20,21,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking
21,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Networking
22,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
23,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
24,22,Male,MARINE ENGINEERING,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
25,20,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
26,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
27,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
28,20,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
29,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
30,18,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
31,21,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking
32,18,Male,STEM,"Network administration, Cybersecurity, or Netw...",Networking
33,21,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
34,21,Female,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
35,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
36,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
37,21,Male,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
38,23,Male,ICT,"Network administration, Cybersecurity, or Netw...",Networking
39,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
40,21,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
41,20,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
42,23,Female,ICT,"Network administration, Cybersecurity, or Netw...",Networking
43,21,Male,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
44,21,Female,STEM,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
45,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
46,23,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
47,20,Female,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
48,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major
49,20,Male,ICT,"Data Analysis, Business Intelligence or Data d...",Business Analytics Major

In [9]:
# df2.shape

In [10]:
# df2.isna().sum()

In [11]:
df2.dtypes

Age                  int64
Sex                 object
Strand in SHS       object
Prefer Skill        object
Major in College    object
dtype: object

In [12]:
from sklearn.preprocessing import LabelEncoder
import pickle;

encoder = LabelEncoder();
df_new = df2.copy();

In [13]:
# sex_encoder = LabelEncoder();
# sex_encoder.fit(df_new['Sex']);
# strand_encoder = LabelEncoder();
# strand_encoder.fit(df_new['Strand in SHS']);
# preferred_skill_encoder = LabelEncoder();
# preferred_skill_encoder.fit(df_new['Prefer Skill'])

In [14]:
# en = LabelEncoder();

# with open('encode_sex.pkl','wb') as f:
#     pickle.dump(sex_encoder, f)

In [15]:
import pickle;

df_new['Sex'] = encoder.fit_transform(df_new['Sex']);

filehandler = open("encode_sex.pkl","wb");
pickle.dump(encoder,filehandler);
filehandler.close()


df_new['Strand in SHS'] = encoder.fit_transform(df_new['Strand in SHS']);

filehandler = open("encode_strand.pkl","wb");
pickle.dump(encoder,filehandler);
filehandler.close()


df_new['Prefer Skill'] = encoder.fit_transform(df_new['Prefer Skill']);

filehandler = open("encode_skill.pkl","wb");
pickle.dump(encoder,filehandler);
filehandler.close()

In [16]:
df_new['Major in College'] = np.where(df_new['Major in College'] == 'Business Analytics Major',1,0)

df_new

    Age  Sex  Strand in SHS  Prefer Skill  Major in College
0    21    0              1             0                 1
1    21    1              1             0                 1
2    21    0              1             0                 1
3    21    1              2             0                 1
4    21    1              4             0                 1
5    21    1              1             0                 1
6    23    0              1             1                 0
7    20    1              1             0                 1
8    23    1              0             1                 0
9    20    1              1             1                 0
10   20    0              1             1                 0
11   21    1              1             1                 0
12   21    1              1             1                 0
13   21    1              1             1                 0
14   22    1              1             0                 1
15   20    1              4             1                 0
16   20    0              1             1                 0
17   23    0              1             1                 0
18   21    0              1             1                 0
19   23    0              1             1                 0
20   21    1              4             1                 0
21   21    0              1             0                 0
22   21    0              1             1                 0
23   21    0              1             0                 1
24   22    1              3             0                 1
25   20    0              1             0                 1
26   21    0              1             1                 0
27   20    1              1             0                 1
28   20    0              1             0                 1
29   21    0              1             1                 0
30   18    1              1             0                 1
31   21    1              4             1                 0
32   18    1              4             1                 0
33   21    0              1             1                 0
34   21    0              4             0                 1
35   23    0              1             1                 0
36   20    1              1             0                 1
37   21    1              4             0                 1
38   23    1              1             1                 0
39   21    0              1             0                 1
40   21    0              1             0                 1
41   20    0              1             1                 0
42   23    0              1             1                 0
43   21    1              4             0                 1
44   21    0              4             0                 1
45   20    1              1             0                 1
46   23    1              1             0                 1
47   20    0              1             0                 1
48   20    1              1             0                 1
49   20    1              1             0                 1

In [17]:
X = df_new.drop(['Major in College'], axis=1);
y = df_new['Major in College'];

# #importing model selection for training and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=50, train_size=.70);

In [18]:
from sklearn.metrics import confusion_matrix;
from sklearn.metrics import RocCurveDisplay;
from sklearn.metrics import classification_report;

In [19]:
def evaluate_model(model, X,y):
    X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=45,
                                                 train_size=.80);
    
    model.fit(X_train, y_train);
    
    print(classification_report(y_test,model.predict(X_test),
                                target_names=['Business Analytics Major','Networking']));
    print(confusion_matrix(y_test,model.predict(X_test),
                          labels=[0,1]));
    print('Training score:',model.score(X_train,y_train));
    print('Test score:',model.score(X_test,y_test));
    RocCurveDisplay.from_estimator(model,X_test,y_test);

In [20]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier();


rf.fit(X_train, y_train);

# dbfile = open ('majorModel.sav','wb');
# pickle.dump(rf,dbfile);

In [21]:
# df_new

In [22]:
# #Changing data types into string
# for col in df2.columns:
#     if (df2[col].dtypes != 'int64'):
#         df2[col] = df2[col].astype('string')

In [23]:
# df2.dtypes

In [24]:
# from sklearn.preprocessing import LabelEncoder
# encoder = LabelEncoder();
# df_new = df2.copy();

In [25]:
# for col in df_new.columns:
#         if(col != 'Age'):
#             df_new[col] = encoder.fit_transform(df_new[col]);

In [26]:
# df_new

In [27]:
# from sklearn.preprocessing import MinMaxScaler
# df_scaled = df_new.copy()
# scaler = MinMaxScaler()

In [28]:
# for col in df_scaled.columns:
#     if(col != 'Major in College'):
#         df_scaled[col] = scaler.fit_transform(df_scaled[col].values.reshape(-1,1));

In [29]:
# df_scaled

In [30]:
# sns.heatmap(df_scaled.corr());

In [31]:
# ...
# # transform the dataset
# from imblearn.over_sampling import SMOTE

# oversample = SMOTE()
# X, y = oversample.fit_resample(X, y)

In [32]:
# from sklearn.metrics import confusion_matrix;
# from sklearn.metrics import RocCurveDisplay;
# from sklearn.metrics import classification_report;

In [33]:
# from sklearn.ensemble import RandomForestClassifier

# rf = RandomForestClassifier();

# evaluate_model(rf, X, y)

In [34]:
# from sklearn.naive_bayes import GaussianNB

# gnb = GaussianNB();
# evaluate_model(gnb, X,y)

In [35]:
# from sklearn.naive_bayes import BernoulliNB

# bnb = BernoulliNB();
# # bnb.fit(X_train,y_train);

# evaluate_model(bnb,X,y)

In [36]:
# from sklearn.tree import DecisionTreeClassifier

# dt = DecisionTreeClassifier();
# # dt.fit(X_train,y_train);

# evaluate_model(dt,X,y)

In [37]:
# from sklearn.neighbors import KNeighborsClassifier

# knn = KNeighborsClassifier();
# # knn.fit(X_train,y_train);

# evaluate_model(knn,X,y)

In [38]:
# from sklearn.linear_model import LogisticRegression

# lr = LogisticRegression();
# # lr.fit(X_train,y_train);

# evaluate_model(lr,X,y)