In [29]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [30]:
#my property

# df1 = pd.read_csv('myproperty-03-05-23.csv');
# df2 = pd.read_csv('myproperty-03-08-23.csv');
# df3 = pd.read_csv('myproperty-03-09-23.csv');
# df4 = pd.read_csv('myproperty-03-10-23.csv');
# df5 = pd.read_csv('myproperty-03-11-23.csv');
# df6 = pd.read_csv('myproperty-03-17-23.csv');
# df7 = pd.read_csv('myproperty-03-18-23.csv');

In [31]:
#lamudi

# df1 = pd.read_csv('lamudi-03-03-23.csv');
# df2 = pd.read_csv('lamudi-03-04-23.csv');
# df3 = pd.read_csv('lamudi-03-05-23.csv');
# df4 = pd.read_csv('lamudi-03-08-23.csv');
# df5 = pd.read_csv('lamudi-03-09-23.csv');
# df6 = pd.read_csv('lamudi-03-10-23.csv');
# df7 = pd.read_csv('lamudi-03-11-23.csv');
# df8 = pd.read_csv('lamudi-03-17-23.csv');
# df9 = pd.read_csv('lamudi-03-18-23.csv');

In [32]:
# dotproperty

df1 = pd.read_csv('dotproperty-03-04-23.csv');
df2 = pd.read_csv('dotproperty-03-05-23.csv');
df3 = pd.read_csv('dotproperty-03-08-23.csv');
df4 = pd.read_csv('dotproperty-03-09-23.csv');
df5 = pd.read_csv('dotproperty-03-11-23.csv');
df6 = pd.read_csv('dotproperty-03-17-23.csv');

In [33]:
# dfs = [df1,df2,df3,df4,df5,df6,df7]
# to_append = ['df2','df3','df4','df5','df6','df7']

In [34]:
# print(len(to_append))

In [35]:
df_new = df1.copy()

In [36]:
# for x in to_append:
#     df_new.append(x)

In [37]:
df_new.append(df2,ignore_index = True)

C:\Users\win10\AppData\Local\Temp\ipykernel_9028\24348522.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_new.append(df2,ignore_index = True)

,Unnamed: 0,name,location,desc,accomodation,price
0,0,2-Bedroom Furnished Apartment for Rent in Bana...,Cebu City\n ...,Property Type: Apartment for RentLocation: Ban...,"['<i class=""icon icon-bedroom""></i> : 2']","₱ 35,000 / month\nNew listing"
1,1,Very Affordable Semi Furnished Apartment for r...,Cebu City\n ...,Location: Banawa Cebu CityVery Affordable Semi...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 12,000 / month\nNew listing"
2,2,Affordable Semi Furnished Apartment for rent i...,Cebu City\n ...,Location: Banawa Cebu CityAffordable Semi Furn...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 12,000 / month\nNew listing"
3,3,2- Bedroom Apartment with Own Gate and Garage ...,"Angeles\n ,...","Rent/ Month: Php 35,000Details:90 sqm more or ...","['<i class=""icon icon-bedroom""></i> : 2']","₱ 35,000 / month"
4,4,Most Affordable 2 Bedroom Apartment for rent i...,Cebu City\n ...,Location: Banawa Cebu City2 Bedroom Apartment ...,"['<i class=""icon icon-bedroom""></i> : 2']","₱ 15,000 / month\nNew listing"
...,...,...,...,...,...,...
1820,920,"LADY BEDSPACE FOR RENT IN AFPOVAI, FORT BONIFA...","Taguig\n , ...","LADY BEDSPACE FOR RENT IN AFPOVAI, FORT BONIFA...","['<i class=""icon icon-bedroom""></i> : 5']","₱ 2,500 / month"
1821,921,Residential/Commercial Building for Lease at S...,Mandaluyong\n ...,Residential Building for Lease in Mandaluyong ...,"['<i class=""icon icon-bedroom""></i> : 43']","₱ 700,000 / month"
1822,922,MACTAN LAPU-LAPU BOUGAINVILLEA Apartment 23 FO...,Lapu-Lapu\n ...,For Rent furnished 25 sqm studio type Bougainv...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 10,000 / month"
1823,923,"1-Bedroom Semi-Furnished Apartment in Banawa, ...",Cebu City\n ...,Property Type: Apartment for RentLocation: nea...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 12,000 / month"
1824,924,For Lease: Brand New Staff House/Condo Bldg 6 ...,"Makati\n , ...",For Lease: Brand New Staff House/Condo Bldg 6 ...,"['<i class=""icon icon-bedroom""></i> : 44']","₱ 1,500,000 / month"

In [38]:
df_new = pd.concat([df1,df2,df3,df4,df5,df6], ignore_index=True)

In [39]:
df_new

,Unnamed: 0,name,location,desc,accomodation,price
0,0,2-Bedroom Furnished Apartment for Rent in Bana...,Cebu City\n ...,Property Type: Apartment for RentLocation: Ban...,"['<i class=""icon icon-bedroom""></i> : 2']","₱ 35,000 / month\nNew listing"
1,1,Very Affordable Semi Furnished Apartment for r...,Cebu City\n ...,Location: Banawa Cebu CityVery Affordable Semi...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 12,000 / month\nNew listing"
2,2,Affordable Semi Furnished Apartment for rent i...,Cebu City\n ...,Location: Banawa Cebu CityAffordable Semi Furn...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 12,000 / month\nNew listing"
3,3,2- Bedroom Apartment with Own Gate and Garage ...,"Angeles\n ,...","Rent/ Month: Php 35,000Details:90 sqm more or ...","['<i class=""icon icon-bedroom""></i> : 2']","₱ 35,000 / month"
4,4,Most Affordable 2 Bedroom Apartment for rent i...,Cebu City\n ...,Location: Banawa Cebu City2 Bedroom Apartment ...,"['<i class=""icon icon-bedroom""></i> : 2']","₱ 15,000 / month\nNew listing"
...,...,...,...,...,...,...
5445,895,Almanza Uno Apartment Room For Rent in Las Piñ...,Las Piñas\n ...,Gated compoundCctvWell ventilated 12 sqm room ...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 5,000 / month"
5446,896,"1BR Apartment for Rent at Infina Towers, Quezo...",Quezon City\n ...,"1BR Apartment for Rent Infina Towers, Quezon C...","['<i class=""icon icon-bedroom""></i> : 1']","₱ 25,000 / month"
5447,897,Apartment Room For Rent at Almanza Uno Las Piñ...,Las Piñas\n ...,Gated compoundCctvWell ventilated 12 sqm room ...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 5,000 / month"
5448,898,"LADY BEDSPACE FOR RENT IN AFPOVAI, FORT BONIFA...","Taguig\n , ...","LADY BEDSPACE FOR RENT IN AFPOVAI, FORT BONIFA...","['<i class=""icon icon-bedroom""></i> : 5']","₱ 2,500 / month"
5449,899,Affordable Room For Rent in Almanza Uno Apartm...,Las Piñas\n ...,Gated compoundCctvWell ventilated 12 sqm room ...,"['<i class=""icon icon-bedroom""></i> : 1']","₱ 5,000 / month"

In [40]:
df_new.shape

(5450, 6)

In [41]:
df_new.duplicated().sum()

1262

In [52]:
import datetime

today_d =  datetime.datetime.now().strftime('%m-%d-%y')
file_name = 'dfa-overall-as-of-' + today_d + '.csv';
file_name

'dfa-overall-as-of-03-17-23.csv'

In [56]:
from pathlib import Path  
filepath = Path(r'C:\Users\win10\Documents\ATT.FEDM\WEB_CRAWLING\appartment_rental\\'+file_name)  
filepath.parent.mkdir(parents=True, exist_ok=True)  
dfa_overall.to_csv(filepath)

In [44]:
dfa1 =  pd.read_csv('lamudi-as-of-03-17-23.csv');
dfa2 =  pd.read_csv('myproperty-as-of-03-17-23.csv');

In [45]:
dfa1

,Unnamed: 0.1,Unnamed: 0,title,location,description,price,features,agent,agent_membership,agent_verified
0,0,0,"Dormitory Spaces for Rent in Santo Tomas, Bata...","Santa Anastacia, Santo Tomas",Consuelo Park Residences (CPR) is a dormitory ...,Contact agent for price,"['Bedroom : 1', 'Bath : 1', 'Floor area : 15 m²']",Oasis FPIP,MEMBER SINCE 2019,verified
1,1,1,"Apartment Building For Rent Located in Molino,...","Molino VII, Bacoor",3 Story Apartment / Condo Building Along Molin...,Contact agent for price,"['Bedrooms : 40', 'Baths : 40', 'Floor area : ...",Clement Dizon,MEMBER SINCE 2016,verified
2,2,2,Rush For Lease: 35-Door Staff House Near Circu...,"Olympia, Makati",Rush For Lease: 35-Door Staff House Near Circu...,"₱ 950,000","['Bedrooms : 35', 'Baths : 35', 'Floor area : ...",Fern Marie Badong,MEMBER SINCE 2017,verified
3,3,3,Discounted Price! For Rent Studio Type Apartme...,"Maypajo, Caloocan","Looking for a new, clean, and affordable apart...","₱ 12,000","['Bedroom : 1', 'Bath : 1', 'Floor area : 26 m²']",JESSA MARTIN,MEMBER SINCE 2022,not verified
4,4,4,RDC Apartment for Rent located at 1156 (c) que...,"Ugong, Valenzuela",2 STOREY\n2 BEDROOM\n1 TOILET AND BATH\nRESIDE...,"₱ 7,000","['Bedrooms : 2', 'Bath : 1', 'Floor area : 36 ...",ROSALIA CRAUWELS,MEMBER SINCE 2021,verified
...,...,...,...,...,...,...,...,...,...,...
14095,14095,1615,Studio Type Rooms for Monthly Rent near SM Mal...,"Baclaran, Parañaque",E & H Residences Rooms for monthly rent Studi...,Contact agent for price,"['Bedroom : 1', 'Bath : 1']",Chloe Chu,MEMBER SINCE 2019,verified
14096,14096,1616,"Studio Apartment for Rent in Plainview, Mandal...","Plainview, Mandaluyong","Studio unit, 1 toilet and bath, unfurnished","₱ 11,000","['Bedroom : 1', 'Bath : 1', 'Floor area : 24 m²']",Pinnacle Real Estate,MEMBER SINCE 2014,verified
14097,14097,1617,Transient Room For Rent in Milagros Subdivisio...,"Dalig, Antipolo",Transient Room For Rent in Antipolo City Rizal...,₱ 500,"['Bedroom : 1', 'Baths : 2']",Malay Meisin Tan,MEMBER SINCE 2016,verified
14098,14098,1618,For Rent: Furnished Studio Unit at The Celerio...,"Tejeros, Makati","The Celerio is located at 4416 Montojo St., Ba...","₱ 14,000","['Bedroom : 1', 'Bath : 1', 'Floor area : 23 m²']",Len Magpusao,MEMBER SINCE 2021,verified
14099,14099,1619,For Rent Eisen Apartel Mla 200mbps nr SM San L...,"Santa Cruz, Manila","Rent : daily, weekly, monthly \nDaily: 1139\...","₱ 1,139","['Bedroom : 1', 'Bath : 1', 'Floor area : 12 m²']",Eisenbuilders Eisen Apartelle,MEMBER SINCE 2014,verified

In [46]:
dfa2

,Unnamed: 0.1,Unnamed: 0,title,location,description,price,features,agent,agent_membership,agent_verified
0,0,0,Transient Room For Rent in Milagros Subdivisio...,"Dalig, Antipolo",Transient Room For Rent in Antipolo City Rizal...,₱ 500,"['Bedroom : 1', 'Baths : 2']",Malay Tan,MEMBER SINCE 2021,not verified
1,1,1,"Dormitory Spaces for Rent in Santo Tomas, Bata...","Santa Anastacia, Santo Tomas",Consuelo Park Residences (CPR) is a dormitory ...,Contact agent for price,"['Bedroom : 1', 'Bath : 1', 'Floor area : 15 m²']",Oasis FPIP,MEMBER SINCE 2019,verified
2,2,2,Beautiful house for sale,"Ilustre, President Roxas",Beautiful house for sale,₱ 123,"['Bedroom : 1', 'Bath : 1', 'Floor area : 123 ...",combo5 user5,MEMBER SINCE 2023,not verified
3,3,3,Studio Type Rooms for Monthly Rent near SM Mal...,"Baclaran, Parañaque",E & H Residences Rooms for monthly rent Studi...,Contact agent for price,"['Bedroom : 1', 'Bath : 1']",Chloe Chu,MEMBER SINCE 2019,verified
4,4,4,2 UNITS FOR RENT APARTMENT IN HERRERA ST. STA ...,Manila,We have 2 UNITS available:\n6th Floor -2 bedro...,"₱ 13,000","['Bedrooms : 2', 'Baths : 2', 'Floor area : 63...",Eva Choi,MEMBER SINCE 2022,not verified
...,...,...,...,...,...,...,...,...,...,...
12325,12325,1765,Condo Sharing Female Bedspace near JP Morgan S...,Makati,Condo Sharing Female Bedspace near JP Morgan S...,"₱ 4,500","['Bedroom : 1', 'Floor area : 18 m²']",condo sharing,MEMBER SINCE 2016,verified
12326,12326,1766,Transient Room 4 sqm in Quezon City,"East Kamias, Quezon City",Transient Room in Cubao Quezon City (Daily)\nN...,Contact agent for price,"['Bedroom : 1', 'Bath : 1', 'Floor area : 4 m²']",Berry Nula,MEMBER SINCE 2015,not verified
12327,12327,1767,accepting lady bed spacers,Angeles,We are accepting lady bed spacers. Perfect for...,"₱ 1,500",['Bedroom : 1'],LINO SANCHEZ,MEMBER SINCE 2016,verified
12328,12328,1768,Condo Sharing Bedspace 4 Rent Merville Paranaq...,Parañaque,Condo Sharing / BedspaceWoodsville Viverde Man...,"₱ 3,900","['Bedroom : 1', 'Floor area : 60 m²']",Rodel Bulan,MEMBER SINCE 2016,verified
12329,12329,1769,2Br 55sqm J&H apartments for rent short or lon...,Cebu,J&H ApartmentsFully furnished apartments for s...,"₱ 25,000","['Bedrooms : 2', 'Bath : 1', 'Floor area : 55 ...",Hilda NA,MEMBER SINCE 2012,not verified

In [47]:
dfa_overall =pd.concat([dfa1,dfa2])

In [55]:
dfa_overall.drop(['Unnamed: 0.1','Unnamed: 0'], axis=1, inplace=True)

In [51]:
dfa_overall.to_csv(filepath)

In [57]:
dfa_overall.isna().sum()

title               0
location            0
description         0
price               0
features            0
agent               0
agent_membership    0
agent_verified      0
dtype: int64

In [58]:
dfa_overall.dtypes

title               object
location            object
description         object
price               object
features            object
agent               object
agent_membership    object
agent_verified      object
dtype: object

In [59]:
dfa_overall.duplicated().sum()

26355

In [61]:
dfa_overall.

AttributeError: 'DataFrame' object has no attribute 'dropduplicate'